export const TYPES = {
  FETCH_CONTACTS: 'FETCH_CONTACTS',
  SET_CONTACTS: 'SET_CONTACTS',
  SET_CONTACT: 'SET_CONTACT',
  GET_CONTACT: 'GET_CONTACT',
  SAVE_CONTACT: 'SAVE_CONTACT',
  ADD_NEW_CONTACT: 'ADD_NEW_CONTACT',
  SAVE_NEW_CONTACT: 'SAVE_NEW_CONTACT',
  EDIT_CONTACT: 'EDIT_CONTACT',
  SAVE_EDITED_CONTACT: 'SAVE_EDITED_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  REMOVE_DELETED_CONTACT: 'REMOVE_DELETED_CONTACT',
  SORT_CONTACTS: 'SORT_CONTACTS',
  CLEAR_SELECTED_CONTACT: 'CLEAR_SELECTED_CONTACT',
  SUBMIT_CONTACT_EDIT: 'SUBMIT_CONTACT_EDIT',
  CANCEL_CONTACT_EDIT: 'CANCEL_CONTACT_EDIT',
};

export const URLS = {
  USERS: 'users',
};
